// This file is auto-generated by @hey-api/openapi-ts

export { getApiDocs, getOpenApiSpec, healthCheck, lookupWord, type Options } from './sdk.gen';
export type { ClientOptions, Conjugations, ErrorResponse, ExampleSentence, GetApiDocsData, GetApiDocsResponse, GetApiDocsResponses, GetOpenApiSpecData, GetOpenApiSpecResponse, GetOpenApiSpecResponses, HealthCheckData, HealthCheckResponse, HealthCheckResponses, HealthResponse, LookupResponse, LookupWordData, LookupWordError, LookupWordErrors, LookupWordResponse, LookupWordResponses } from './types.gen';
