// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, GetV2EntriesByIdData, GetV2EntriesByIdErrors, GetV2EntriesByIdResponses, GetV2KanjiByLiteralData, GetV2KanjiByLiteralErrors, GetV2KanjiByLiteralResponses, GetV2LookupData, GetV2LookupErrors, GetV2LookupResponses, PostV2LookupBatchData, PostV2LookupBatchErrors, PostV2LookupBatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Look up one dictionary token
 */
export const getV2Lookup = <ThrowOnError extends boolean = false>(options?: Options<GetV2LookupData, ThrowOnError>) => (options?.client ?? client).get<GetV2LookupResponses, GetV2LookupErrors, ThrowOnError>({ url: '/v2/lookup', ...options });

/**
 * Look up tokenizer tokens in batch
 */
export const postV2LookupBatch = <ThrowOnError extends boolean = false>(options: Options<PostV2LookupBatchData, ThrowOnError>) => (options.client ?? client).post<PostV2LookupBatchResponses, PostV2LookupBatchErrors, ThrowOnError>({
    url: '/v2/lookup/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a canonical entry by Yori ID
 */
export const getV2EntriesById = <ThrowOnError extends boolean = false>(options: Options<GetV2EntriesByIdData, ThrowOnError>) => (options.client ?? client).get<GetV2EntriesByIdResponses, GetV2EntriesByIdErrors, ThrowOnError>({ url: '/v2/entries/{id}', ...options });

/**
 * Get kanji details by literal
 */
export const getV2KanjiByLiteral = <ThrowOnError extends boolean = false>(options: Options<GetV2KanjiByLiteralData, ThrowOnError>) => (options.client ?? client).get<GetV2KanjiByLiteralResponses, GetV2KanjiByLiteralErrors, ThrowOnError>({ url: '/v2/kanji/{literal}', ...options });
