// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiDocsData, GetApiDocsResponses, GetOpenApiSpecData, GetOpenApiSpecResponses, HealthCheckData, HealthCheckResponses, LookupWordData, LookupWordErrors, LookupWordResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * OpenAPI specification
 */
export const getOpenApiSpec = <ThrowOnError extends boolean = false>(options?: Options<GetOpenApiSpecData, ThrowOnError>) => (options?.client ?? client).get<GetOpenApiSpecResponses, unknown, ThrowOnError>({ url: '/openapi.yaml', ...options });

/**
 * Interactive API reference (Scalar UI)
 */
export const getApiDocs = <ThrowOnError extends boolean = false>(options?: Options<GetApiDocsData, ThrowOnError>) => (options?.client ?? client).get<GetApiDocsResponses, unknown, ThrowOnError>({ url: '/docs', ...options });

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Lookup a Japanese word
 *
 * Looks up a Japanese word by exact match on kanji (`word`) or reading.
 * Returns `404` when the word does not exist, or when no translation is available for the requested language.
 *
 */
export const lookupWord = <ThrowOnError extends boolean = false>(options: Options<LookupWordData, ThrowOnError>) => (options.client ?? client).get<LookupWordResponses, LookupWordErrors, ThrowOnError>({ url: '/v1/lookup', ...options });
