// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type TargetLanguage = 'en' | 'de' | 'ko' | 'zh-cn' | 'zh-tw';

export type ErrorResponse = {
    error: string;
};

export type LookupToken = {
    query?: string;
    word?: string;
    surface?: string;
    lemma?: string;
    reading?: string;
    pos?: string;
};

export type MatchedAlias = {
    aliasId: string;
    surface: string;
    reading?: string;
    entryId: string;
    formId?: string;
    readingId?: string;
    matchType: string;
    score: number;
};

export type LookupEntry = {
    id: string;
    word: string;
    reading: string;
    pos: Array<string>;
    definitions: Array<string>;
};

export type LookupResult = {
    matched: MatchedAlias | null;
    entries: Array<LookupEntry>;
};

export type SourceRef = {
    kind: 'jmdict' | 'jmnedict' | 'kanjidic2' | 'wiktionary' | 'tatoeba' | 'manual' | 'ai';
    sourceId?: string;
    license?: string;
    importedAt: string;
    model?: string;
    promptVersion?: string;
    inputRefs?: Array<string>;
    reviewStatus?: 'unreviewed' | 'approved' | 'rejected';
};

export type Form = {
    id: string;
    text: string;
    normalizedText: string;
    script: string;
    isPrimary: boolean;
    tags: Array<string>;
    sourceRefs: Array<SourceRef>;
};

export type Reading = {
    id: string;
    text: string;
    normalizedText: string;
    system: string;
    isPrimary: boolean;
    appliesToFormIds: 'all' | Array<string>;
    tags: Array<string>;
    sourceRefs: Array<SourceRef>;
};

export type Gloss = {
    id: string;
    lang: TargetLanguage;
    text: string;
    sourceType: 'source' | 'manual' | 'ai';
    reviewStatus: 'unreviewed' | 'approved' | 'rejected';
    sourceRefs: Array<SourceRef>;
};

export type Example = {
    id: string;
    senseId?: string;
    lang: TargetLanguage;
    japanese: string;
    translation: string;
    sourceRefs: Array<SourceRef>;
};

export type Sense = {
    id: string;
    order: number;
    partOfSpeech: Array<string>;
    appliesToFormIds: 'all' | Array<string>;
    appliesToReadingIds: 'all' | Array<string>;
    domain: Array<string>;
    register: Array<string>;
    misc: Array<string>;
    glosses: Array<Gloss>;
    examples: Array<Example>;
    sourceRefs: Array<SourceRef>;
};

export type EntryDetail = {
    id: string;
    language: string;
    entryType: string;
    primaryForm: string;
    primaryReading: string;
    forms: Array<Form>;
    readings: Array<Reading>;
    senses: Array<Sense>;
    ranking: {
        [key: string]: unknown;
    };
    sourceRefs: Array<SourceRef>;
};

export type KanjiDetail = {
    id: string;
    literal: string;
    meanings: Array<{
        lang: TargetLanguage;
        text: string;
        sourceRefs: Array<SourceRef>;
    }>;
    readings: Array<{
        type: string;
        text: string;
        sourceRefs: Array<SourceRef>;
    }>;
    stats: {
        [key: string]: unknown;
    };
    sourceRefs: Array<SourceRef>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetV2LookupData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Generic lookup text. Alias of the legacy `word` parameter.
         */
        query?: string;
        /**
         * Compatibility alias for `query`.
         */
        word?: string;
        /**
         * Token surface from a tokenizer.
         */
        surface?: string;
        /**
         * Dictionary/base form from a tokenizer.
         */
        lemma?: string;
        /**
         * Kana or katakana reading from a tokenizer.
         */
        reading?: string;
        /**
         * Target gloss language. Defaults to `en`.
         */
        lang?: TargetLanguage;
        limit?: number;
    };
    url: '/v2/lookup';
};

export type GetV2LookupErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type GetV2LookupError = GetV2LookupErrors[keyof GetV2LookupErrors];

export type GetV2LookupResponses = {
    /**
     * Lookup result
     */
    200: LookupResult;
};

export type GetV2LookupResponse = GetV2LookupResponses[keyof GetV2LookupResponses];

export type PostV2LookupBatchData = {
    body: {
        lang?: TargetLanguage;
        limit?: number;
        tokens: Array<LookupToken>;
    };
    path?: never;
    query?: never;
    url: '/v2/lookup/batch';
};

export type PostV2LookupBatchErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type PostV2LookupBatchError = PostV2LookupBatchErrors[keyof PostV2LookupBatchErrors];

export type PostV2LookupBatchResponses = {
    /**
     * Batch lookup result
     */
    200: {
        results: Array<LookupResult & {
            token: LookupToken;
        }>;
    };
};

export type PostV2LookupBatchResponse = PostV2LookupBatchResponses[keyof PostV2LookupBatchResponses];

export type GetV2EntriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Optional language filter for glosses and examples.
         */
        lang?: TargetLanguage;
    };
    url: '/v2/entries/{id}';
};

export type GetV2EntriesByIdErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type GetV2EntriesByIdError = GetV2EntriesByIdErrors[keyof GetV2EntriesByIdErrors];

export type GetV2EntriesByIdResponses = {
    /**
     * Canonical entry detail
     */
    200: EntryDetail;
};

export type GetV2EntriesByIdResponse = GetV2EntriesByIdResponses[keyof GetV2EntriesByIdResponses];

export type GetV2KanjiByLiteralData = {
    body?: never;
    path: {
        literal: string;
    };
    query?: {
        /**
         * Optional language filter for meanings.
         */
        lang?: TargetLanguage;
    };
    url: '/v2/kanji/{literal}';
};

export type GetV2KanjiByLiteralErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type GetV2KanjiByLiteralError = GetV2KanjiByLiteralErrors[keyof GetV2KanjiByLiteralErrors];

export type GetV2KanjiByLiteralResponses = {
    /**
     * Canonical kanji detail
     */
    200: KanjiDetail;
};

export type GetV2KanjiByLiteralResponse = GetV2KanjiByLiteralResponses[keyof GetV2KanjiByLiteralResponses];
