// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.yori-dict.com' | 'http://localhost:3000' | (string & {});
};

export type HealthResponse = {
    status: 'ok';
};

export type LookupResponse = {
    /**
     * Kanji form
     */
    word: string;
    /**
     * Hiragana reading
     */
    reading: string;
    /**
     * Romanized reading
     */
    romaji: string;
    partOfSpeech: Array<string>;
    definitions: Array<string>;
    conjugations?: Conjugations;
    examples: Array<ExampleSentence>;
};

export type Conjugations = {
    dictionary: string;
    polite: string;
    negative: string;
    past: string;
    te: string;
};

export type ExampleSentence = {
    japanese: string;
    translation: string;
};

export type ErrorResponse = {
    error: string;
};

export type GetOpenApiSpecData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.yaml';
};

export type GetOpenApiSpecResponses = {
    /**
     * OpenAPI 3.0 YAML document
     */
    200: string;
};

export type GetOpenApiSpecResponse = GetOpenApiSpecResponses[keyof GetOpenApiSpecResponses];

export type GetApiDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs';
};

export type GetApiDocsResponses = {
    /**
     * HTML page with Scalar API reference UI
     */
    200: string;
};

export type GetApiDocsResponse = GetApiDocsResponses[keyof GetApiDocsResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * API is healthy
     */
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type LookupWordData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Japanese word in kanji, hiragana, or katakana.
         */
        word: string;
        /**
         * Translation language code. Default is `en`.
         * Canonical values: `en`, `de`, `ko`, `zh-cn`, `zh-tw`.
         * Accepted aliases: `zh-CN`, `zh-TW`, `zh_cn`, `zh_tw`, `zh-hans`, `zh-hant`.
         *
         */
        lang?: 'en' | 'de' | 'ko' | 'zh-cn' | 'zh-tw' | 'zh-CN' | 'zh-TW' | 'zh_cn' | 'zh_tw' | 'zh-hans' | 'zh-hant';
    };
    url: '/v1/lookup';
};

export type LookupWordErrors = {
    /**
     * Invalid request (missing word or invalid language)
     */
    400: ErrorResponse;
    /**
     * Word not found or language translation unavailable
     */
    404: ErrorResponse;
    /**
     * Unexpected server error
     */
    500: ErrorResponse;
};

export type LookupWordError = LookupWordErrors[keyof LookupWordErrors];

export type LookupWordResponses = {
    /**
     * Lookup result
     */
    200: LookupResponse;
};

export type LookupWordResponse = LookupWordResponses[keyof LookupWordResponses];
